import Head from "next/head";
import Image from "next/image";
import { gsap } from "gsap";

//import { ScrollTrigger } from "gsap/ScrollTrigger";

import Slider from "../components/Slider";
import Navbar from "../components/Navbar";
import SlideShow from "../components/SlideShow";
import Drawer from "../components/Drawer";
import Category from "../components/Category";
import MiddleSection from "../components/MiddleSection";

export default function Home() {
  //useLayoutEffect(() => {}, []);
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer />

      <div className="wrapper">
        <Slider />
        <Navbar />
        <SlideShow />
        <MiddleSection />
        <Category />
      </div>
    </div>
  );
}
